'use client';
import { useId,useState } from 'react';
import styles from './overview.module.css';
const colors=['#ff6794','#eac593','#a6cad5','#c994e2','#9bd2bd'];
const labels={users:'New accounts',creators:'Creators',subscribers:'Subscribers',designs:'Designs',bookings:'Booking requests',openReports:'Open reports',labProcessing:'Lab processing',lab:'Lab requests',reports:'Reports'};
const pretty=v=>labels[v]||String(v).replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());
const number=v=>Number(v||0).toLocaleString();
const day=v=>new Date(v+'T00:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short',timeZone:'UTC'});
function Panel({title,note,children,wide=false}){return <section className={`${styles.panel} ${wide?styles.wide:''}`}><header><h2>{title}</h2>{note&&<p>{note}</p>}</header>{children}</section>}
export function Trend({title,note,rows,series}){
 const [chosen,setChosen]=useState(series[0]?.key),[point,setPoint]=useState(null);const key=series.some(s=>s.key===chosen)?chosen:series[0]?.key;
 const id=useId();const actual=point===null?rows.length-1:Math.min(point,rows.length-1);
 const selected=rows[actual];const top=Math.max(1,...rows.map(r=>Number(r[key]||0)));const yMax=Math.max(1,Math.ceil(top/4)*4);
 const width=760,left=48,right=16,height=225,bottom=32;const x=i=>left+i*(width-left-right)/Math.max(1,rows.length-1),y=v=>12+(height-bottom-12)*(1-Number(v||0)/yMax);
 const points=rows.map((r,i)=>`${x(i)},${y(r[key])}`).join(' '),total=rows.reduce((n,r)=>n+Number(r[key]||0),0);
 const color=colors[Math.max(0,series.findIndex(s=>s.key===key))%colors.length];
 return <Panel title={title} note={note} wide><div className={styles.chartToolbar}><div className={styles.series} role="group" aria-label={`${title} metric`}>{series.map((s,i)=><button key={s.key} aria-pressed={s.key===key} onClick={()=>{setChosen(s.key);setPoint(null)}}><span style={{background:colors[i%colors.length]}}/>{s.label}</button>)}</div><div className={styles.total}><strong>{number(total)}</strong><span>{series.find(s=>s.key===key)?.label} in range</span></div></div>
 <svg viewBox={`0 0 ${width} ${height}`} className={styles.line} role="img" aria-labelledby={id}><title id={id}>{title}: {number(total)} {series.find(s=>s.key===key)?.label}. Daily values are available below.</title>
 {[0,1,2,3,4].map(i=><g key={i}><line x1={left} y1={y(yMax*i/4)} x2={width-right} y2={y(yMax*i/4)} stroke="#ffffff18"/><text x={left-10} y={y(yMax*i/4)+4} textAnchor="end">{number(yMax*i/4)}</text></g>)}
 {total>0&&<polygon points={`${left},${y(0)} ${points} ${x(rows.length-1)},${y(0)}`} fill={color} opacity=".09"/>}<polyline points={points} fill="none" stroke={color} strokeWidth="2.5" strokeLinejoin="round"/>
 {selected&&<><line x1={x(actual)} y1={12} x2={x(actual)} y2={y(0)} stroke="#ffffff50" strokeDasharray="4 4"/><circle cx={x(actual)} cy={y(selected[key])} r="4" fill={color} stroke="#350211" strokeWidth="2"/></>}
 {rows.map((r,i)=><rect key={r.date} x={x(i)-12} y="0" width="24" height={height-bottom} fill="transparent" onMouseEnter={()=>setPoint(i)} onClick={()=>setPoint(i)}/>)}
 {[0,Math.floor((rows.length-1)/2),rows.length-1].filter((v,i,a)=>a.indexOf(v)===i).map(i=><text key={i} x={x(i)} y={height-7} textAnchor={i===0?'start':i===rows.length-1?'end':'middle'}>{day(rows[i].date)}</text>)}</svg>
 {selected&&<div className={styles.readout}><span>{day(selected.date)} · <strong>{number(selected[key])}</strong> {series.find(s=>s.key===key)?.label.toLowerCase()}</span><input type="range" aria-label={`Inspect day in ${title}`} min="0" max={rows.length-1} value={actual} onChange={e=>setPoint(Number(e.target.value))}/></div>}
 {!total&&<p className={styles.empty}>No activity in this range. The chart shows real zero values.</p>}
 <details className={styles.data}><summary>View daily data</summary><div><table><caption>{title} · daily totals</caption><thead><tr><th>Date</th>{series.map(s=><th key={s.key}>{s.label}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.date}><th scope="row">{day(r.date)}</th>{series.map(s=><td key={s.key}>{number(r[s.key])}</td>)}</tr>)}</tbody></table></div></details></Panel>
}
function Distribution({title,note,items=[]}){
 const id=useId(),total=items.reduce((n,x)=>n+Number(x.value),0);let start=0;
 const segments=items.map((r,i)=>{const from=start;start+=Number(r.value)/Math.max(1,total)*100;return `${colors[i%colors.length]} ${from}% ${start}%`});
 return <Panel title={title} note={note}><div className={styles.distribution}><div className={styles.donut} role="img" aria-labelledby={id} style={{background:total?`conic-gradient(${segments.join(',')})`:'#ffffff14'}}><div><strong>{number(total)}</strong><span>Total</span></div></div><ul id={id}>{items.map((r,i)=><li key={r.label}><span className={styles.dot} style={{background:colors[i%colors.length]}}/><span>{pretty(r.label)}</span><strong>{number(r.value)}</strong><small>{total?Math.round(Number(r.value)/total*100):0}%</small></li>)}</ul></div>{!total&&<p className={styles.empty}>No records in this range.</p>}</Panel>
}
function Bars({title,note,items=[],visitors=false}){
 const max=Math.max(1,...items.map(x=>Number(x.value)));
 return <Panel title={title} note={note}><div className={styles.bars}>{items.map((r,i)=><div key={r.label}><div className={styles.barLabel}><span>{pretty(r.label)}</span><strong>{number(r.value)}{visitors&&<small> · {number(r.users)} users</small>}</strong></div><div className={styles.track}><span style={{width:`${Number(r.value)/max*100}%`,background:colors[i%colors.length]}}/></div></div>)}</div>{!items.length&&<p className={styles.empty}>No activity recorded yet.</p>}</Panel>
}
export default function Overview({data,days,onRange}){
 const trendKeys=['users','designs','bookings','lab','reports'].filter(k=>k in (data.trend?.[0]||{}));const behavior=data.behavior;const setup=data.operations?.setup;
 const metricLabels={...labels,users:'Users',bookings:'Bookings'};
 return <div className={styles.overview}><div className={styles.range}><div><span className={styles.kicker}>Connected {data.environment}</span><p>Dubai time · Staff, test accounts and closed accounts excluded.</p></div><div role="group" aria-label="Analytics date range">{[7,30].map(n=><button key={n} aria-pressed={days===n} onClick={()=>onRange(n)}>Last {n} days</button>)}</div></div>
 <div className={styles.metrics}>{['users','creators','subscribers','bookings','openReports','labProcessing'].filter(key=>key in data.counts).map(key=><article key={key}><span>{metricLabels[key]||pretty(key)}</span><strong>{number(data.counts[key])}</strong><small>Current total</small></article>)}</div>
 <div className={styles.grid}>{data.counts.designs!==undefined&&<Panel title="Design library" note="Total designs in LaQue; separate from paid subscribers."><strong className={styles.libraryTotal}>{number(data.counts.designs)}</strong><p>Designs</p></Panel>}{data.labPlan&&<Panel title="Nail Lab subscription" note="Purchases and subscription status remain provider verified."><p>$5 / month · 15 designs per billing month</p><p>Extra tokens: 30 designs for $10 · 100 designs for $25</p><p>1 new generation uses 1 token. Generated images cannot be edited.</p></Panel>}{data.trend?.length>0&&<Trend key={days} title="Activity over time" note="New records per day. Select a metric to inspect its daily trend." rows={data.trend} series={trendKeys.map(key=>({key,label:pretty(key)}))}/>}
 {data.operations&&<><Distribution title="Booking outcomes" note="Current status of requests created in this range; not a conversion funnel." items={data.operations.bookings}/><Distribution title="Lab request status" note="Released requests include recovery and cancellation; they are not all failures." items={data.operations.lab}/></>}
 {setup&&<Panel title="Profile setup" note="Current setup state of accounts created in this range."><div className={styles.setup}><strong>{setup.joined?Math.round(setup.completed/setup.joined*100):0}%</strong><span>Completed profile setup</span></div><BarsContent items={[{label:'Accounts created',value:setup.joined},{label:'Setup completed',value:setup.completed},{label:'Setup incomplete',value:setup.joined-setup.completed}]}/></Panel>}
 {data.content&&<Distribution title="Design publication" note="Current publication state of designs created in this range." items={data.content}/>}</div>
 {behavior&&<><div className={styles.sectionHeading}><div><span className={styles.kicker}>User behavior</span><h2>How people use LaQue</h2></div><span className={styles.status}>{behavior.views?'First-party analytics':'Awaiting opted-in activity'}</span></div>
 <p className={styles.explanation}>Screen metrics cover signed-in users who enabled usage statistics. They are not all app users. Historical screen visits are unavailable; tracking starts with the updated app.{behavior.trackingSince&&` Earliest retained event: ${new Date(behavior.trackingSince).toLocaleDateString('en-GB',{timeZone:'Asia/Dubai'})}.`}</p>
 <div className={styles.metrics}>{[{label:'Tracked active users',value:behavior.trackedUsers,note:'Unique opted-in users in range'},{label:'App sessions',value:behavior.sessions,note:'Temporary sessions; renewed after 30 minutes without a screen visit'},{label:'Screen visits',value:behavior.views,note:'Screen entries, not time spent'},{label:'Returned on another day',value:behavior.returningUsers,note:'Users active on at least two Dubai dates'}].map(r=><article key={r.label}><span>{r.label}</span><strong>{number(r.value)}</strong><small>{r.note}</small></article>)}</div>
 <div className={styles.grid}><Trend key={'behavior-'+days} title="Tracked engagement" note="Daily unique opted-in users and screen entries." rows={behavior.daily} series={[{key:'users',label:'Active users'},{key:'views',label:'Screen visits'}]}/><Bars title="Most visited screens" note="Screen entries and unique opted-in visitors." items={behavior.screens} visitors/><Distribution title="Sessions by platform" note="Reported app platform; not a device fingerprint." items={behavior.platforms}/><Bars title="Product actions" note="Retained operational records created in range; undone saves/follows are no longer counted." items={behavior.actions}/><Panel title="Reading the data"><ul className={styles.notes}><li>Historical account, booking and Lab records populate activity charts immediately.</li><li>Screen analytics are optional, off by default and use a 30-day reporting window. Expired history is removed by daily cleanup. Turning them off removes that user’s screen history.</li><li>No search text, chat content, images, location or individual behavior history appears here.</li><li>Counts describe activity, not revenue, payment success, time spent or cohort retention.</li></ul></Panel></div></>}
 <footer className={styles.footer}>Updated {new Date(data.generatedAt).toLocaleString('en-GB',{timeZone:'Asia/Dubai'})} · Aggregate data · Refresh to load new activity.</footer></div>
}
function BarsContent({items}){const max=Math.max(1,...items.map(x=>x.value));return <div className={styles.bars}>{items.map(r=><div key={r.label}><div className={styles.barLabel}><span>{r.label}</span><strong>{number(r.value)}</strong></div><div className={styles.track}><span style={{width:`${r.value/max*100}%`,background:colors[0]}}/></div></div>)}</div>}
