'use client';
import styles from './admin.module.css';
const label=k=>({id:'Account ID',is_verified:'Profile verification badge',is_private:'Private profile',onboarding_complete:'Profile setup complete',show_saves:'Saves visible',deletion_started_at:'Account closed at',credit_balance:'Purchased design tokens',active:'Active subscription',monthlyRemaining:'Monthly designs remaining',renewsAt:'Billing period ends',store:'Billing store'}[k]||k.replaceAll('_',' ').replace(/^./,c=>c.toUpperCase()));
const value=(v,k)=>(k.endsWith('_at')||k==='renewsAt')&&v&&Number.isFinite(new Date(v).getTime())?new Date(v).toLocaleString('en-GB',{timeZone:'Asia/Dubai',dateStyle:'medium',timeStyle:'short'})+' · Dubai':v===null||v===undefined||v===''?'Not provided':Array.isArray(v)?v.length?v.join(', '):'None':typeof v==='boolean'?v?'Yes':'No':String(v);
function Fields({data,keys}){return <dl className={styles.userFields}>{keys.map(k=><div key={k}><dt>{label(k)}</dt><dd>{value(data?.[k],k)}</dd></div>)}</dl>}
export default function UserDetails({detail,owner}){
 const p=detail.profile;
 return <div className={styles.userDetails}>
 <div className={styles.userIdentity}>{p.banner_url&&<img className={styles.userBanner} src={p.banner_url} alt="Profile banner"/>}<div>{p.avatar_url&&<img className={styles.userAvatar} src={p.avatar_url} alt="Profile photo"/>}<h3>{p.display_name||'LaQue user'}</h3><p>@{p.username||'No username'} · {p.account_type}</p><span className={styles.badge}>{p.deletion_started_at?'Closed':detail.suspension?.suspended?'Suspended':'Active'}</span></div></div>
 <div className={styles.grid}><article><h3>Profile & contact</h3><Fields data={p} keys={['id','email','phone_number','preferred_contact','bio','location','booking_area','specialties','is_verified','created_at']}/></article>
 <article><h3>Account & privacy</h3><Fields data={p} keys={['onboarding_complete','email_confirmed_at','is_private','deletion_started_at',...(owner?['message_permission','show_saves','age_confirmed_at','privacy_accepted_at','privacy_policy_version']:[])]}/>{owner&&<Fields data={{usage_statistics:detail.usagePreference?.enabled===true}} keys={['usage_statistics']}/>}</article>
 {owner&&<article><h3>Sign-in information</h3>{detail.authentication?<Fields data={detail.authentication} keys={['email','phone','email_confirmed_at','phone_confirmed_at','last_sign_in_at','created_at','providers','authenticator_verified']}/>:<p>Authentication account is unavailable.</p>}</article>}
 <article><h3>Related activity</h3><Fields data={detail.activity||{}} keys={Object.keys(detail.activity||{})}/></article>
 {owner&&<article><h3>Subscription, tokens & account usage</h3>{detail.labSubscription&&<Fields data={detail.labSubscription} keys={['active','monthlyRemaining','renewsAt','store']}/>}<Fields data={p} keys={['credit_balance','weekly_uploads','week_reset_at','referral_code','referred_by']}/><p>Token corrections and purchase history are in Subscriptions & Tokens. Corrections never grant membership.</p></article>}
 </div>
 <details className={styles.editor} open><summary>Creator services & working hours</summary><p>Time zone: {detail.bookingSettings?.time_zone||'Not configured'}</p>{!detail.services?.length&&<p>No services configured.</p>}{detail.services?.map(s=><article key={s.id}><h3>{s.name} · {s.is_active?'Visible':'Hidden'}</h3><p>{s.description||'No description'}</p><p>{s.duration_minutes} minutes · AED {s.price} total · AED {s.deposit_amount||0} deposit · AED {Number(s.price)-Number(s.deposit_amount||0)} balance</p></article>)}{!detail.hours?.length&&<p>No working hours configured.</p>}{detail.hours?.map((h,i)=><p key={i}>{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][h.day_of_week]} · {h.is_active?`${h.start_time} – ${h.end_time}`:'Closed'}</p>)}</details>
 {owner&&<details className={styles.editor}><summary>Personal nail preferences & booking notes</summary><Fields data={p} keys={['nail_shape','nail_length','nail_colors','nail_finishes','nail_techniques','occasions','budget_range','booking_notes','allergies','product_sensitivities','removal_needed','nail_condition','skin_undertone','hand_photo_url']}/>{detail.privateNotes?.health&&<><h4>Current health notes</h4><Fields data={detail.privateNotes.health} keys={['allergies','product_sensitivities','removal_needed','share_with_tech','updated_at']}/></>}{detail.privateNotes?.booking&&<Fields data={detail.privateNotes.booking} keys={['booking_notes','updated_at']}/>}</details>}
 </div>
}
