import {fireEvent,render,screen} from '@testing-library/react-native';
import type {PurchasesPackage} from 'react-native-purchases';
import {CreditsView,type CreditsViewProps} from '../src/features/credits/credits-view';
import {creditPackages} from '../src/features/credits/model';
jest.mock('react-native-safe-area-context',()=>require('react-native-safe-area-context/jest/mock').default);
const props=():CreditsViewProps=>({balance:30,subscription:{active:true,monthlyRemaining:0,purchasedTokens:30,renewsAt:'2026-11-08T00:00:00Z',store:'APP_STORE'},packs:[{id:'laque_lab_monthly_5',kind:'subscription',credits:15,price:'AED 18.49'},{id:'laque_lab_tokens_30',kind:'credits',credits:30,price:'AED 36.99'},{id:'laque_lab_tokens_100',kind:'credits',credits:100,price:'AED 91.99'}],onBack:jest.fn(),onBuy:jest.fn(),onCheck:jest.fn(),onRetry:jest.fn(),onRestore:jest.fn()});
test('subscribers select localized token packs',async()=>{const p=props();await render(<CreditsView {...p}/>);await fireEvent.press(screen.getByRole('radio',{name:'100 design tokens, AED 91.99'}));await fireEvent.press(screen.getByRole('button',{name:'Buy 100 design tokens · AED 91.99'}));expect(p.onBuy).toHaveBeenCalledWith('laque_lab_tokens_100');});
test('non-subscribers get a monthly paywall, not a token purchase',async()=>{const p=props();p.subscription={...p.subscription!,active:false};await render(<CreditsView {...p}/>);expect(screen.getByRole('radio',{name:'30 design tokens, AED 36.99'})).toBeDisabled();await fireEvent.press(screen.getByRole('button',{name:'Subscribe · AED 18.49/month'}));expect(p.onBuy).toHaveBeenCalledWith('laque_lab_monthly_5');expect(screen.queryByText(/free variation/i)).toBeNull();});
test.each([{pending:true},{balance:null},{busy:true},{loading:true},{unavailable:true},{error:'Offline'},{subscription:{active:true,monthlyRemaining:3,purchasedTokens:30,renewsAt:null,store:'APP_STORE'}}])('unsafe store state cannot purchase: %p',async extra=>{const p={...props(),...extra};await render(<CreditsView {...p}/>);expect(screen.getByRole('button',{name:/Buy 30 design tokens|Awaiting verification/})).toBeDisabled();expect(p.onBuy).not.toHaveBeenCalled();});
test('restore and status recovery remain explicit',async()=>{const p=props();await render(<CreditsView {...p} pending/>);await fireEvent.press(screen.getByRole('button',{name:'Check purchase status'}));await fireEvent.press(screen.getByRole('button',{name:'Restore purchases'}));expect(p.onCheck).toHaveBeenCalledTimes(1);expect(p.onRestore).toHaveBeenCalledTimes(1);expect(p.onBuy).not.toHaveBeenCalled();});
test('only exact monthly/consumable products and matching store types are accepted',()=>{const catalog=[{store:'APP_STORE',product_id:'laque_lab_monthly_5',kind:'subscription',credits:15},{store:'APP_STORE',product_id:'laque_lab_tokens_30',kind:'credits',credits:30},{store:'APP_STORE',product_id:'legacy',kind:'credits',credits:15}];const packages=[{product:{identifier:'laque_lab_monthly_5',priceString:'$5',subscriptionPeriod:'P1M',productCategory:'SUBSCRIPTION',productType:'AUTO_RENEWABLE_SUBSCRIPTION'}},{product:{identifier:'laque_lab_tokens_30',priceString:'$10',subscriptionPeriod:null,productCategory:'NON_SUBSCRIPTION',productType:'CONSUMABLE'}},{product:{identifier:'legacy',priceString:'$10',subscriptionPeriod:null,productCategory:'NON_SUBSCRIPTION',productType:'CONSUMABLE'}}] as unknown as PurchasesPackage[];expect(creditPackages(catalog,packages,'APP_STORE').map(x=>x.id)).toEqual(['laque_lab_monthly_5','laque_lab_tokens_30']);expect(creditPackages(catalog,packages,'PLAY_STORE')).toEqual([]);});

test('Google subscription packages match the configured base plan and reject the Apple identity',()=>{
 const catalog=[{store:'PLAY_STORE',product_id:'laque_lab_monthly_5:monthly',kind:'subscription',credits:15},{store:'PLAY_STORE',product_id:'laque_lab_monthly_5',kind:'subscription',credits:15}];
 const packages=catalog.map(p=>({product:{identifier:p.product_id,priceString:'$5',subscriptionPeriod:'P1M',productCategory:'SUBSCRIPTION',productType:'AUTO_RENEWABLE_SUBSCRIPTION'}})) as unknown as PurchasesPackage[];
 expect(creditPackages(catalog,packages,'PLAY_STORE').map(x=>x.id)).toEqual(['laque_lab_monthly_5:monthly']);
});
