export const profileAssets = {
  publicCover: require("../../../assets/figma/profiles/65ac4.png"),
  ownerCover: require("../../../assets/figma/profiles/ce0f1.png"),
  back: require("../../../assets/figma/profiles/b9cb8.svg"),
  share: require("../../../assets/figma/profiles/165ca.svg"),
  more: require("../../../assets/figma/profiles/d501b.svg"),
  location: require("../../../assets/figma/profiles/0b6d6.svg"),
  clock: require("../../../assets/figma/profiles/3c2cf.svg"),
  heart: require("../../../assets/figma/profiles/8b812.svg"),
  account: require("../../../assets/figma/profiles/ed233.svg"),
  lock: require("../../../assets/figma/profiles/00799.svg"),
  calendar: require("../../../assets/figma/profiles/88463.svg"),
  saved: require("../../../assets/figma/profiles/5ab84.svg"),
  favorites: require("../../../assets/figma/profiles/b04e7.svg"),
  folder: require("../../../assets/figma/profiles/79f58.svg"),
  credits: require("../../../assets/figma/profiles/9168a.svg"),
  private: require("../../../assets/figma/profiles/d2545.svg"),
  edit: require("../../../assets/figma/profiles/048f4.svg"),
  notifications: require("../../../assets/figma/profiles/5c4af.svg"),
  safety: require("../../../assets/figma/profiles/1d758.svg"),
  payment: require("../../../assets/figma/profiles/a3234.svg"),
  help: require("../../../assets/figma/profiles/9edd5.svg"),
  settingLines: [
    require("../../../assets/figma/profiles/21b9b.svg"),
    require("../../../assets/figma/profiles/48d9e.svg"),
  ],
};
