import { beforeEach,it,expect,vi } from 'vitest'
const mock=vi.hoisted(()=>({getSessionUser:vi.fn(),from:vi.fn(),rpc:vi.fn()}))
vi.mock('@/lib/auth',()=>({...mock,serviceClient:{from:mock.from,rpc:mock.rpc}}))
import { adminIdentity,requireSection } from '@/lib/admin/auth'
import { GET as legacyGet,POST as legacyPost } from '@/app/api/admin-profiles/route'
const user={id:'00000000-0000-4000-8000-000000000971',email_confirmed_at:'2026-10-08',factors:[{factor_type:'totp',status:'verified'}]}
function req(aal='aal2') {return new Request('https://example.invalid/api/admin/identity',{headers:{authorization:'Bearer x.'+Buffer.from(JSON.stringify({aal})).toString('base64url')+'.signature'}})}
beforeEach(()=>{vi.resetAllMocks();mock.getSessionUser.mockResolvedValue(user);mock.from.mockImplementation(()=>({select:()=>({eq:()=>({maybeSingle:async()=>({data:{active:true,role:'owner'},error:null})})})}));mock.rpc.mockResolvedValue({data:false,error:null})})
it('rejects signed-out users, ordinary accounts, revoked membership and suspended staff',async()=>{mock.getSessionUser.mockResolvedValueOnce(null);await expect(adminIdentity(req())).rejects.toMatchObject({status:401});for(const staff of [null,{active:false,role:'owner'},{active:true,role:'invented'}]){mock.from.mockImplementationOnce(()=>({select:()=>({eq:()=>({maybeSingle:async()=>({data:staff,error:null})})})}));await expect(adminIdentity(req())).rejects.toMatchObject({status:403})}mock.rpc.mockResolvedValueOnce({data:true});await expect(adminIdentity(req())).rejects.toMatchObject({status:403})})
it('requires server-verified session, AAL2 and a verified authenticator factor',async()=>{await expect(adminIdentity(req('aal1'))).rejects.toMatchObject({code:'MFA_REQUIRED'});expect(await adminIdentity(req('aal1'),{identityOnly:true})).toMatchObject({mfa:false});mock.getSessionUser.mockResolvedValueOnce({...user,factors:[{factor_type:'phone',status:'verified'}]});await expect(adminIdentity(req())).rejects.toMatchObject({code:'MFA_REQUIRED'});expect((await adminIdentity(req())).mfa).toBe(true)})
it('scopes role access and rechecks membership on every request',async()=>{mock.from.mockImplementation(()=>({select:()=>({eq:()=>({maybeSingle:async()=>({data:{active:true,role:'support'}})})})}));const i=await adminIdentity(req());expect(()=>requireSection(i,'credits')).toThrow();expect(()=>requireSection(i,'reports')).toThrow();expect(()=>requireSection(i,'bookings')).not.toThrow();await adminIdentity(req());expect(mock.from).toHaveBeenCalledTimes(2)})
it('legacy admin writes are retired even for verified owners',async()=>{expect((await legacyGet(req())).status).toBe(410);expect((await legacyPost(req())).status).toBe(410)})
