import {beforeEach,it,expect,vi} from 'vitest'
import {database,ok} from '../helpers/supabase'
const mock=vi.hoisted(()=>({db:null,user:vi.fn()}))
vi.mock('@/lib/auth',()=>({get serviceClient(){return mock.db},getSessionUser:mock.user}))
import {GET,POST} from '@/app/api/mobile/analytics/route'
import {adminGet} from '@/lib/admin/data'
const uid='00000000-0000-4000-8000-000000000801',event={id:'00000000-0000-4000-8000-000000000802',sessionId:'00000000-0000-4000-8000-000000000803',screen:'home',platform:'ios'}
const req=body=>new Request('https://beta.invalid/api/mobile/analytics',{method:'POST',body:JSON.stringify(body)})
beforeEach(()=>{mock.user.mockResolvedValue({id:uid});mock.db=database(()=>ok(null),()=>ok(true))})
it('requires verified session and does not expose another account preference',async()=>{mock.user.mockResolvedValue(null);expect((await GET(new Request('https://beta.invalid'))).status).toBe(401);expect((await POST(req(event))).status).toBe(401);expect(mock.db.calls).toHaveLength(0);expect(mock.db.rpc).not.toHaveBeenCalled()})
it('defaults to opt-out; derives account identity from session for preferences and events',async()=>{expect(await (await GET(new Request('https://beta.invalid'))).json()).toEqual({enabled:false});expect(mock.db.calls[0].filters).toContainEqual(['eq','user_id',uid]);expect((await POST(req({action:'preference',enabled:true}))).status).toBe(200);expect(mock.db.rpc).toHaveBeenCalledWith('app_analytics_preference',{p_user:uid,p_enabled:true});expect((await POST(req(event))).status).toBe(200);expect(mock.db.rpc).toHaveBeenCalledWith('app_analytics_record',{p_user:uid,p_id:event.id,p_session:event.sessionId,p_screen:'home',p_platform:'ios'})})
it('rejects arbitrary metadata, spoofed IDs, raw paths and oversized input',async()=>{for(const body of [{...event,userId:uid},{...event,search:'private terms'},{...event,screen:'/conversation/secret-id'},{...event,id:[event.id]},{action:'preference',enabled:'true'},null,[]])expect((await POST(req(body))).status).toBe(400);expect((await POST(req({...event,raw:'x'.repeat(2000)}))).status).toBe(413);expect(mock.db.rpc).not.toHaveBeenCalled()})
it('sanitizes database errors without provider or account details',async()=>{mock.db=database(()=>({error:{message:'private provider secret'}}),()=>({error:{message:'private provider secret'}}));const r=await POST(req(event));expect(r.status).toBe(503);expect(JSON.stringify(await r.json())).not.toContain('secret')})
it('passes only verified actor and supported date range to service aggregate',async()=>{mock.db=database(()=>ok(null),()=>ok({counts:{users:1},trend:[]}));const result=await adminGet('overview',null,new URLSearchParams('days=7'),{user:{id:uid},role:'owner'});expect(result.counts.users).toBe(1);expect(mock.db.rpc).toHaveBeenCalledWith('admin_analytics_overview',{p_actor:uid,p_days:7});await expect(adminGet('overview',null,new URLSearchParams('days=365'),{user:{id:uid}})).rejects.toThrow(/range/);expect(mock.db.rpc).toHaveBeenCalledTimes(2)})
