import {beforeAll,afterAll,it,expect} from 'vitest'
import {readFile} from 'node:fs/promises'
import {createSecurityDatabase} from '../helpers/security-database'
let db
const ids=Array.from({length:6},(_,i)=>`00000000-0000-4000-8000-000000000${970+i}`)
const [owner,support,moderator,user,creator,secondOwner]=ids
const design='00000000-0000-4000-8000-000000000980',report='00000000-0000-4000-8000-000000000981'
beforeAll(async()=>{db=await createSecurityDatabase();await db.exec('alter table auth.users add column email_confirmed_at timestamptz');for(const n of ['202610080027_pinterest_budget.sql','202610080028_pinterest_budget_recovery.sql','202610080029_pinterest_pilot_allowance.sql','202610080030_admin_operations.sql','202610080031_pinterest_oauth.sql','202610080032_admin_private_media.sql'])await db.exec(await readFile(new URL('../../supabase/migrations/'+n,import.meta.url),'utf8'));for(const id of ids){await db.query('insert into auth.users(id,email_confirmed_at) values($1,now())',[id]);await db.query("update profiles_data set display_name='Beta fixture',credit_balance=10 where id=$1",[id])}await db.query("insert into admin_staff(user_id,role) values($1,'owner'),($2,'support'),($3,'moderator'),($4,'owner')",[owner,support,moderator,secondOwner]);await db.query("insert into designs(id,title,created_by,is_published) values($1,'Nails',$2,true)",[design,creator]);await db.query("insert into mobile_reports(id,reporter_id,target_type,target_id,reason) values($1,$2,'design',$3,'Reported design')",[report,user,design])},30000)
afterAll(()=>db?.close())
const mutate=(actor,action,target,data={},reason='Beta verification reason')=>db.as('service_role',null,'select admin_mutate($1,$2,$3,$4,$5) as result',[actor,action,target,reason,data])
it('service-only records, RPCs and legacy flags cannot grant browser admin powers',async()=>{for(const role of ['anon','authenticated']){await expect(db.as(role,user,'select * from admin_staff')).rejects.toThrow(/permission denied/);await expect(db.as(role,user,"select admin_mutate($1,'credits',$2,'test reason','{}')",[user,user])).rejects.toThrow(/permission denied/)}await db.query('update profiles_data set is_admin=true where id=$1',[user]);expect((await db.query('select is_admin from profiles_data where id=$1',[user])).rows[0].is_admin).toBe(false)})
it('requires role, reason and current active membership',async()=>{await expect(mutate(support,'credits',user,{delta:1,key:crypto.randomUUID()})).rejects.toThrow(/FORBIDDEN/);await expect(mutate(moderator,'suspend',user,{suspended:true})).rejects.toThrow(/FORBIDDEN/);await expect(mutate(owner,'credits',user,{delta:1,key:crypto.randomUUID()},'')).rejects.toThrow(/REASON/);await db.query('update admin_staff set active=false where user_id=$1',[support]);await expect(mutate(support,'note',user,{type:'user',body:'Case note'})).rejects.toThrow(/FORBIDDEN/);await db.query('update admin_staff set active=true where user_id=$1',[support])})
it('corrects credits with one durable record under replay and rejects changed payloads',async()=>{const key=crypto.randomUUID();await Promise.all([mutate(owner,'credits',user,{delta:3,key}),mutate(owner,'credits',user,{delta:3,key})]);expect((await db.query('select credit_balance from profiles_data where id=$1',[user])).rows[0].credit_balance).toBe(13);expect((await db.query('select count(*)::int n from admin_credit_corrections where idempotency_key=$1',[key])).rows[0].n).toBe(1);await expect(mutate(owner,'credits',user,{delta:4,key})).rejects.toThrow(/CONFLICT/);await expect(mutate(owner,'credits',user,{delta:-100,key:crypto.randomUUID()})).rejects.toThrow(/INSUFFICIENT/);await db.as('service_role',null,'select reserve_generation($1,$2)',[crypto.randomUUID(),user]);await mutate(owner,'credits',user,{delta:-2,key:crypto.randomUUID()});expect((await db.query('select credit_balance from profiles_data where id=$1',[user])).rows[0].credit_balance).toBe(10)})
it('protects final owner and only allows verified Support/Moderator assignments',async()=>{await mutate(owner,'staff',secondOwner,{active:false});await expect(mutate(owner,'staff',owner,{active:false})).rejects.toThrow(/FINAL_OWNER/);await expect(mutate(owner,'staff',user,{role:'owner',active:true})).rejects.toThrow(/INVALID_ROLE/);await mutate(owner,'staff',support,{role:'support',active:true})})
it('hides discovery and detail reads; restores with existing author privacy',async()=>{await mutate(moderator,'moderate',report,{hidden:true});expect((await db.as('authenticated',user,'select id from designs where id=$1',[design])).rows).toHaveLength(0);await mutate(moderator,'moderate',report,{hidden:false});expect((await db.as('authenticated',user,'select id from designs where id=$1',[design])).rows).toHaveLength(1);await db.query('update profiles_data set is_private=true where id=$1',[creator]);expect((await db.as('authenticated',user,'select id from designs where id=$1',[design])).rows).toHaveLength(0);await db.query('update profiles_data set is_private=false where id=$1',[creator])})
it('suspension hides public identity and blocks generation reservation while restoration is reversible',async()=>{await mutate(owner,'suspend',creator,{suspended:true});expect((await db.as('authenticated',user,'select id from profiles where id=$1',[creator])).rows).toHaveLength(0);await expect(db.as('service_role',null,'select reserve_generation($1,$2)',[crypto.randomUUID(),creator])).rejects.toThrow(/SUSPENDED/);await expect(db.as('authenticated',creator,"insert into designs(title,created_by) values('new',$1)",[creator])).rejects.toThrow(/SUSPENDED/);await mutate(owner,'suspend',creator,{suspended:false});expect((await db.as('authenticated',user,'select id from designs where id=$1',[design])).rows).toHaveLength(1)})
it('keeps drafts private and rejects stale concurrent Home saves and publishes',async()=>{const content=(await db.query('select published from admin_home')).rows[0].published;await mutate(moderator,'home-draft',null,{version:1,content:{...content,announcements:[{id:'test',title:'New',body:'Announcement'}]}});expect((await db.query('select published from admin_home')).rows[0].published.announcements).toEqual([]);await expect(mutate(owner,'home-draft',null,{version:1,content})).rejects.toThrow(/CONFLICT/);await expect(mutate(owner,'home-publish',null,{version:1})).rejects.toThrow(/CONFLICT/);await mutate(owner,'home-publish',null,{version:2});expect((await db.query('select published,revision from admin_home')).rows[0]).toMatchObject({revision:2,published:{announcements:[{title:'New'}]}})})
it('OAuth attempts are browser/owner bound, expiring and one-use',async()=>{await db.as('service_role',null,"select pinterest_admin_change($1,'start','test connection',$2)",[owner,{stateHash:'teststate',browserHash:'browser'}]);const claim=(browser,id=owner)=>db.as('service_role',null,'select claim_pinterest_oauth($1,$2,$3) result',['teststate',browser,id]);expect((await claim('wrong')).rows[0].result).toBe(null);expect((await claim('browser',user)).rows[0].result).toBe(null);expect((await claim('browser')).rows[0].result).not.toBe(null);expect((await claim('browser')).rows[0].result).toBe(null)})
it('refresh has a shared lease and disconnect prevents a late refresh from restoring credentials',async()=>{await db.query("update pinterest_connection set status='connected',expires_at=now()-interval '1 hour'");const a=(await db.as('service_role',null,'select claim_pinterest_refresh() token')).rows[0].token;expect(a).toBeTruthy();expect((await db.as('service_role',null,'select claim_pinterest_refresh() token')).rows[0].token).toBe(null);await db.as('service_role',null,"select pinterest_admin_change($1,'disconnect','disconnect test','{}')",[owner]);expect((await db.as('service_role',null,"select finish_pinterest_refresh($1,$2) result",[a,{access:'cipher',refresh:'cipher',expires:new Date().toISOString(),refreshExpires:new Date().toISOString()}])).rows[0].result).toBe(false);expect((await db.query('select status,access_cipher from pinterest_connection')).rows[0]).toEqual({status:'disconnected',access_cipher:null})})

it('private-bucket image access follows ordinary design RLS for public, draft, private and hidden states',async()=>{
 const path=creator+'/admin/00000000-0000-4000-8000-000000000987.webp'
 await db.query("update designs set image_url=$1,is_published=true where id=$2",['https://beta.supabase.co/storage/v1/object/public/mobile-uploads/'+path,design])
 await db.query("insert into storage.objects(bucket_id,name) values('mobile-uploads',$1)",[path])
 const bytes=(role='authenticated')=>db.as(role,role==='anon'?null:user,'select name from storage.objects where name=$1',[path])
 expect((await bytes()).rows).toHaveLength(1);expect((await bytes('anon')).rows).toHaveLength(1)
 await db.query('update designs set is_published=false where id=$1',[design]);expect((await bytes()).rows).toHaveLength(0)
 await db.query('update designs set is_published=true where id=$1',[design]);await db.query('update profiles_data set is_private=true where id=$1',[creator]);expect((await bytes()).rows).toHaveLength(0)
 await db.query('update profiles_data set is_private=false where id=$1',[creator]);await mutate(moderator,'moderate',report,{hidden:true});expect((await bytes()).rows).toHaveLength(0)
 await mutate(moderator,'moderate',report,{hidden:false});expect((await bytes()).rows).toHaveLength(1)
 expect((await db.as('authenticated',user,"select can_read_design_object('mobile-uploads',$1) allowed",[creator+'/%'])).rows[0].allowed).toBe(false)
})
