import {beforeAll,afterAll,it,expect} from 'vitest'
import {readFile} from 'node:fs/promises'
import {createSecurityDatabase} from '../helpers/security-database'
let db;const ids=Array.from({length:5},(_,i)=>`00000000-0000-4000-8000-000000000${850+i}`);const [owner,support,moderator,user,excluded]=ids;
beforeAll(async()=>{db=await createSecurityDatabase();await db.exec('alter table auth.users add column email_confirmed_at timestamptz,add column email text');for(const n of ['202610080027_pinterest_budget.sql','202610080028_pinterest_budget_recovery.sql','202610080029_pinterest_pilot_allowance.sql','202610080030_admin_operations.sql','202610080031_pinterest_oauth.sql','202610080032_admin_private_media.sql','202610080033_admin_analytics.sql'])await db.exec(await readFile(new URL('../../supabase/migrations/'+n,import.meta.url),'utf8'));for(const [i,id] of ids.entries()){await db.query('insert into auth.users(id,email,email_confirmed_at) values($1,$2,now())',[id,i===4?'fixture@laque-beta.example':`analytics-${i}@example.invalid`]);await db.query("update profiles_data set onboarding_complete=true where id=$1",[id])}await db.query("insert into admin_staff(user_id,role) values($1,'owner'),($2,'support'),($3,'moderator')",[owner,support,moderator]);await db.query("insert into designs(title,created_by,is_published) values('Real design',$1,true),('Staff design',$2,true),('Excluded fixture',$3,true)",[user,owner,excluded])},30000)
afterAll(()=>db?.close());const overview=(actor,days=7)=>db.as('service_role',null,'select admin_analytics_overview($1,$2) result',[actor,days]);const record=(id=crypto.randomUUID(),session=crypto.randomUUID(),screen='home')=>db.as('service_role',null,"select app_analytics_record($1,$2,$3,$4,'ios') recorded",[user,id,session,screen]);const preference=enabled=>db.as('service_role',null,'select app_analytics_preference($1,$2)',[user,enabled]);
it('keeps raw events and aggregate functions service-only',async()=>{for(const role of ['anon','authenticated']){await expect(db.as(role,user,'select * from app_analytics_events')).rejects.toThrow(/permission denied/);await expect(db.as(role,user,'select * from app_analytics_preferences')).rejects.toThrow(/permission denied/);await expect(db.as(role,owner,'select admin_analytics_overview($1,7)',[owner])).rejects.toThrow(/permission denied/)}})
it('scopes aggregate keys to current staff role and excludes staff/test accounts',async()=>{const o=(await overview(owner)).rows[0].result;expect(o.counts.users).toBe(1);expect(o.counts.designs).toBe(1);expect(o.trend).toHaveLength(7);expect(o.behavior).toBeDefined();expect(o.trend.reduce((n,r)=>n+r.users,0)).toBe(1);const s=(await overview(support)).rows[0].result;expect(s.behavior).toBeUndefined();expect(s.content).toBeUndefined();expect(s.operations).toBeDefined();const m=(await overview(moderator)).rows[0].result;expect(m.counts.users).toBeUndefined();expect(m.trend[0].users).toBeUndefined();expect(m.operations).toBeUndefined();expect(m.behavior).toBeUndefined();expect(m.content).toBeDefined();await expect(overview(user)).rejects.toThrow(/FORBIDDEN/);await expect(overview(owner,365)).rejects.toThrow(/INVALID_RANGE/)})
it('requires consent and deduplicates replay without cross-user id assignment',async()=>{expect((await record()).rows[0].recorded).toBe(false);await preference(true);const id=crypto.randomUUID();expect((await record(id)).rows[0].recorded).toBe(true);expect((await record(id)).rows[0].recorded).toBe(false);expect((await db.query('select count(*)::int n from app_analytics_events')).rows[0].n).toBe(1);await preference(false);expect((await db.query('select count(*)::int n from app_analytics_events')).rows[0].n).toBe(0)})
it('calculates unique users, sessions, returning dates and Dubai day boundaries',async()=>{await preference(true);const session=crypto.randomUUID(),today=(await db.query("select (now() at time zone 'Asia/Dubai')::date::text as date_value")).rows[0].date_value;await db.query("insert into app_analytics_events(id,user_id,session_id,screen,platform,created_at) values($1,$2,$3,'home','ios',$4::date::timestamp at time zone 'Asia/Dubai'),($5,$2,$3,'search','ios',($4::date::timestamp at time zone 'Asia/Dubai')-interval '1 hour')",[crypto.randomUUID(),user,session,today,crypto.randomUUID()]);const b=(await overview(owner)).rows[0].result.behavior;expect(b).toMatchObject({trackedUsers:1,sessions:1,views:2,returningUsers:1});expect(b.daily.at(-1)).toMatchObject({date:today,users:1,views:1});expect(b.daily.at(-2).views).toBe(1);expect(JSON.stringify(b)).not.toContain(user);await preference(false)})
it('bounds ingestion and rejects arbitrary event categories',async()=>{await preference(true);await expect(record(crypto.randomUUID(),crypto.randomUUID(),'private chat text')).rejects.toThrow(/INVALID/);for(let i=0;i<30;i++)expect((await record()).rows[0].recorded).toBe(true);expect((await record()).rows[0].recorded).toBe(false);await preference(false)})
it('prunes expired events and erases opt-in and history immediately on account closure',async()=>{await preference(true);await db.query("insert into app_analytics_events(id,user_id,session_id,screen,platform,created_at) values($1,$2,$3,'home','ios',now()-interval '31 days')",[crypto.randomUUID(),user,crypto.randomUUID()]);await overview(owner);expect((await db.query('select count(*)::int n from app_analytics_events')).rows[0].n).toBe(0);await record();await db.query('update profiles_data set deletion_started_at=now() where id=$1',[user]);expect((await db.query('select count(*)::int n from app_analytics_events')).rows[0].n).toBe(0);expect((await db.query('select count(*)::int n from app_analytics_preferences')).rows[0].n).toBe(0);expect((await record()).rows[0].recorded).toBe(false)})
