import {beforeAll,afterAll,it,expect} from 'vitest'
import {readFile} from 'node:fs/promises'
import {createSecurityDatabase} from '../helpers/security-database'
let db;const [owner,support,moderator,user]=Array.from({length:4},(_,i)=>`00000000-0000-4000-8000-000000000${910+i}`);
beforeAll(async()=>{db=await createSecurityDatabase();await db.exec('alter table auth.users add column email_confirmed_at timestamptz,add column email text,add column last_sign_in_at timestamptz');for(const n of ['202610080027_pinterest_budget.sql','202610080028_pinterest_budget_recovery.sql','202610080029_pinterest_pilot_allowance.sql','202610080030_admin_operations.sql','202610080034_admin_user_directory.sql'])await db.exec(await readFile(new URL('../../supabase/migrations/'+n,import.meta.url),'utf8'));for(const [i,id]of[owner,support,moderator,user].entries())await db.query('insert into auth.users(id,email,email_confirmed_at,last_sign_in_at) values($1,$2,now(),now())',[id,`directory-${i}@example.invalid`]);await db.query("insert into admin_staff(user_id,role) values($1,'owner'),($2,'support'),($3,'moderator')",[owner,support,moderator]);await db.query("update profiles_data set display_name='Visible',username='test.user',phone_number='test phone',allergies='Private note',credit_balance=17,stripe_customer_id='provider secret' where id=$1",[user])},30000)
afterAll(()=>db?.close())
const directory=(actor,args={})=>db.as('service_role',null,'select admin_user_directory($1,$2,$3,$4,$5,$6) result',[actor,args.q||'',args.type||'',args.offset||0,args.limit||25,args.id||null]);
const log=(actor,role,section)=>db.as('service_role',null,"select admin_export_log($1,$2,$3,'Verified testing reason',1,null)",[actor,role,section]);
it('service-only directory rejects ordinary, moderator, revoked and suspended staff',async()=>{for(const role of['anon','authenticated'])await expect(db.as(role,owner,'select admin_user_directory($1)',[owner])).rejects.toThrow(/permission denied/);for(const id of[user,moderator])await expect(directory(id)).rejects.toThrow(/FORBIDDEN/);await db.query('update admin_staff set active=false where user_id=$1',[support]);await expect(directory(support)).rejects.toThrow(/FORBIDDEN/);await db.query('update admin_staff set active=true where user_id=$1',[support]);await db.query('insert into admin_suspensions(user_id,suspended) values($1,true)',[support]);await expect(directory(support)).rejects.toThrow(/FORBIDDEN/);await db.query('delete from admin_suspensions where user_id=$1',[support])})
it('returns allowlisted Owner information and a narrower Support view; never raw auth/provider fields',async()=>{const o=(await directory(owner,{id:user})).rows[0].result[0];expect(o).toMatchObject({phone_number:'test phone',allergies:'Private note',credit_balance:17,email:'directory-3@example.invalid'});expect(o).not.toHaveProperty('stripe_customer_id');expect(o.last_sign_in_at).toBeTruthy();const s=(await directory(support,{id:user})).rows[0].result[0];expect(s).not.toHaveProperty('allergies');expect(s).not.toHaveProperty('credit_balance');expect(s.last_sign_in_at).toBeNull()})
it('searches email and paginates deterministically, with validated limits',async()=>{const a=(await directory(owner,{q:'directory-3@'})).rows[0].result;expect(a.map(x=>x.id)).toEqual([user]);expect((await directory(owner,{offset:4,limit:1})).rows[0].result).toEqual([]);await expect(directory(owner,{type:'invented'})).rejects.toThrow(/INVALID/);await expect(directory(owner,{limit:501})).rejects.toThrow(/INVALID/)})
it('records permitted exports and denies Support user exports, wrong roles and revocation',async()=>{await log(owner,'owner','users');await log(support,'support','bookings');await expect(log(support,'support','users')).rejects.toThrow(/FORBIDDEN/);await expect(log(owner,'support','users')).rejects.toThrow(/FORBIDDEN/);await db.query('update admin_staff set active=false where user_id=$1',[owner]);await expect(log(owner,'owner','users')).rejects.toThrow(/FORBIDDEN/);expect((await db.query("select count(*)::int n from admin_actions where action='export'")).rows[0].n).toBe(2)})
