import {beforeAll,afterAll,it,expect} from 'vitest';
import {readFile} from 'node:fs/promises';
import {createSecurityDatabase} from '../helpers/security-database';
let db;const owner='00000000-0000-4000-8000-000000000701',user='00000000-0000-4000-8000-000000000702';
const call=(sql,args=[])=>db.as('service_role',null,sql,args);const scalar=async(sql,args=[])=>Object.values((await call(sql,args)).rows[0])[0];
beforeAll(async()=>{db=await createSecurityDatabase();await db.exec('alter table auth.users add column email text');for(const n of ['202610080027_pinterest_budget.sql','202610080028_pinterest_budget_recovery.sql','202610080029_pinterest_pilot_allowance.sql','202610080030_admin_operations.sql','202610080035_lab_subscription.sql','202610080036_lab_play_base_plan.sql'])await db.exec(await readFile(new URL('../../supabase/migrations/'+n,import.meta.url),'utf8'));await db.query('insert into auth.users(id) values($1),($2)',[owner,user]);await db.query("insert into admin_staff(user_id,role) values($1,'owner')",[owner]);await db.query('update profiles_data set credit_balance=30 where id=$1',[user])},30000);
afterAll(()=>db?.close());
const claim=id=>scalar('select claim_generation($1,$2,null,$3)',[id,user,'a'.repeat(64)]);
const status=()=>scalar('select lab_subscription_status($1)',[user]);
const subscription=async()=>{await db.query("insert into mobile_entitlements(user_id,store,product_id,plan_id,expires_at,refunded) values($1,'APP_STORE','laque_lab_monthly_5','premium',now()+interval '30 days',false)",[user]);await db.query("insert into lab_monthly_allowances(user_id,store,product_id,period_start,period_end) values($1,'APP_STORE','laque_lab_monthly_5',now()-interval '1 day',now()+interval '30 days')",[user])};
it('requires a real current subscription even with purchased tokens and rejects free variations',async()=>{expect(await claim('00000000-0000-4000-8000-000000000711')).toBe('subscription_required');expect(await status()).toMatchObject({active:false,purchasedTokens:30});await subscription();expect(await scalar('select reserve_generation($1,$2,$3)',['00000000-0000-4000-8000-000000000712',user,'00000000-0000-4000-8000-000000000713'])).toBe(false)});
it('uses the 15 monthly allowance first, then tokens; retry/release are idempotent',async()=>{const id='00000000-0000-4000-8000-000000000714';expect(await claim(id)).toBe('claimed');expect(await claim(id)).toBe('reserved');expect(await status()).toMatchObject({monthlyRemaining:14,purchasedTokens:30});expect(await scalar('select release_generation($1)',[id])).toBe(true);expect(await scalar('select release_generation($1)',[id])).toBe(false);expect(await status()).toMatchObject({monthlyRemaining:15,purchasedTokens:30});await db.query('update lab_monthly_allowances set used=15 where user_id=$1',[user]);const other='00000000-0000-4000-8000-000000000715';expect(await claim(other)).toBe('claimed');expect(await status()).toMatchObject({monthlyRemaining:0,purchasedTokens:29});await scalar('select release_generation($1)',[other]);expect(await status()).toMatchObject({purchasedTokens:30})});
it('expiry preserves tokens and accepted intent recovery but blocks new work',async()=>{await db.query('update lab_monthly_allowances set used=0 where user_id=$1',[user]);const id='00000000-0000-4000-8000-000000000716';expect(await claim(id)).toBe('claimed');await db.query("update mobile_entitlements set expires_at=now()-interval '1 second' where user_id=$1",[user]);expect(await claim(id)).toBe('reserved');expect(await claim('00000000-0000-4000-8000-000000000717')).toBe('subscription_required');await scalar('select release_generation($1)',[id]);expect(await status()).toMatchObject({active:false,purchasedTokens:30});});
it('new products start disabled and internal bypass paths/service-private monthly data are denied',async()=>{expect(await scalar("select count(*)::int from mobile_store_products where active and product_id like 'laque_lab_%'")).toBe(0);for(const role of ['anon','authenticated'])await expect(db.as(role,user,'select lab_subscription_status($1)',[user])).rejects.toThrow(/permission denied/);await expect(scalar('select reserve_generation_before_deletion_guard($1,$2,null)',['00000000-0000-4000-8000-000000000718',user])).rejects.toThrow(/permission denied/)});
it('verified renewals reset only the monthly bucket and repeated snapshots preserve usage',async()=>{const start=new Date(Date.now()-3600000).toISOString(),end=new Date(Date.now()+30*86400000).toISOString();const snapshot=[{store:'APP_STORE',product_id:'laque_lab_monthly_5',expires_at:end,purchased_at:start,refunded:false}];const reconcile=async entries=>{const token=await scalar('select claim_mobile_billing($1)',[user]);expect(await scalar('select finish_mobile_billing($1,$2,$3,$4)',[user,token,JSON.stringify(entries),'[]'])).toBe(true)};await reconcile(snapshot);expect(await status()).toMatchObject({active:true,monthlyRemaining:15,purchasedTokens:30});await db.query("update lab_monthly_allowances set used=7 where user_id=$1 and period_start=$2",[user,start]);await reconcile(snapshot);expect(await status()).toMatchObject({monthlyRemaining:8,purchasedTokens:30});await reconcile([{...snapshot[0],refunded:true}]);expect(await status()).toMatchObject({active:false,purchasedTokens:30});await reconcile(snapshot);expect(await status()).toMatchObject({active:false,purchasedTokens:30})});
it('subscription refund does not debit independently purchased tokens',async()=>{const event={store:'APP_STORE',environment:'SANDBOX',product_id:'laque_lab_monthly_5',transaction_id:'subscription-transaction',original_transaction_id:'original-subscription',purchased_at_ms:Date.now()-3600000,type:'INITIAL_PURCHASE',id:'subscription-event'};await db.query('select apply_mobile_store_transaction($1,$2,false)',[user,JSON.stringify(event)]);await db.query('select apply_mobile_store_transaction($1,$2,true)',[user,JSON.stringify({...event,id:'subscription-refund'})]);expect(await scalar('select credit_balance from profiles_data where id=$1',[user])).toBe(30);expect(await scalar("select refunded from mobile_store_transactions where transaction_id='subscription-transaction'")).toBe(true)});
it('suspension and wrong role do not grant subscription access or private admin totals',async()=>{await db.query("insert into admin_suspensions(user_id,suspended) values($1,true)",[user]);expect(await status()).toMatchObject({active:false});await expect(scalar('select admin_lab_summary($1)',[user])).rejects.toThrow(/FORBIDDEN/);expect(await scalar('select admin_lab_summary($1)',[owner])).toMatchObject({subscribers:0,plan:{monthlyUsd:5,monthlyDesigns:15}});for(const role of ['anon','authenticated'])for(const sql of ['select claim_generation($1,$2,null,$3)','select release_generation($1)'])await expect(db.as(role,user,sql,sql.includes('claim')?['00000000-0000-4000-8000-000000000719',user,'a'.repeat(64)]:['00000000-0000-4000-8000-000000000719'])).rejects.toThrow(/permission denied/)});

it('Google Play base-plan identity receives and spends the same monthly allowance',async()=>{
 await db.query('update admin_suspensions set suspended=false where user_id=$1',[user]);
 const snapshot=[{store:'PLAY_STORE',product_id:'laque_lab_monthly_5:monthly',expires_at:new Date(Date.now()+30*86400000).toISOString(),purchased_at:new Date(Date.now()-3600000).toISOString(),refunded:false}];
 const token=await scalar('select claim_mobile_billing($1)',[user]);
 expect(await scalar('select finish_mobile_billing($1,$2,$3,$4)',[user,token,JSON.stringify(snapshot),'[]'])).toBe(true);
 expect(await status()).toMatchObject({active:true,monthlyRemaining:15,store:'PLAY_STORE',purchasedTokens:30});
 expect(await scalar('select claim_generation($1,$2,null,$3)',['00000000-0000-4000-8000-000000000799',user,'b'.repeat(64)])).toBe('claimed');
 expect(await status()).toMatchObject({monthlyRemaining:14,purchasedTokens:30});
});

it('generated outputs and linked gallery additions are immutable while publishing metadata can change',async()=>{
 const gen='00000000-0000-4000-8000-000000000881',design='00000000-0000-4000-8000-000000000882';
 await db.query('insert into nail_lab_generations(id,user_id,image_url) values($1,$2,$3)',[gen,user,'original-output']);
 await expect(db.query('update nail_lab_generations set image_url=$1 where id=$2',['edited-output',gen])).rejects.toThrow(/GENERATED_IMAGE_IMMUTABLE/);
 await db.query('insert into designs(id,created_by,title,image_url,source_generation_id) values($1,$2,$3,$4,$5)',[design,user,'Generated design','original-output',gen]);
 await db.query('update designs set title=$1 where id=$2',['Publishing title',design]);
 await expect(db.query('update designs set image_url=$1 where id=$2',['edited-output',design])).rejects.toThrow(/GENERATED_IMAGE_IMMUTABLE/);
 await expect(db.query('insert into design_images(design_id,image_url,image_order) values($1,$2,0)',[design,'new closeup'])).rejects.toThrow(/GENERATED_IMAGE_IMMUTABLE/);
 expect((await db.query('select title,image_url from designs where id=$1',[design])).rows[0]).toMatchObject({title:'Publishing title',image_url:'original-output'});
});
