export const searchAssets = {
  background: require("../../../assets/backgrounds/search-background-4k.png"),
  filter: require("../../../assets/figma/search/04ff1.svg"),
  sort: require("../../../assets/figma/search/66992.svg"),
  close: require("../../../assets/figma/search/5eecf.svg"),
  savedHeart: require("../../../assets/figma/search/33b7c.svg"),
  artistHeart: require("../../../assets/figma/search/8b812.svg"),
  location: require("../../../assets/figma/search/e6652.svg"),
  rating: require("../../../assets/figma/search/c875b.svg"),
};
export const colorAssets = {
  Black: require("../../../assets/figma/search/c9008.svg"),
  White: require("../../../assets/figma/search/8983a.svg"),
  Pink: require("../../../assets/figma/search/3e216.svg"),
  Nude: require("../../../assets/figma/search/ee389.svg"),
  Mauve: require("../../../assets/figma/search/5ffe2.svg"),
  Berry: require("../../../assets/figma/search/8c7ee.svg"),
  Red: require("../../../assets/figma/search/aa669.svg"),
  Purple: require("../../../assets/figma/search/1e9f8.svg"),
  Lilac: require("../../../assets/figma/search/a5f47.svg"),
  Blue: require("../../../assets/figma/search/cd7da.svg"),
  Teal: require("../../../assets/figma/search/ae895.svg"),
  Green: require("../../../assets/figma/search/c814f.svg"),
  Sage: require("../../../assets/figma/search/fb459.svg"),
  Brown: require("../../../assets/figma/search/325a2.svg"),
  Caramel: require("../../../assets/figma/search/e2643.svg"),
  Gold: require("../../../assets/figma/search/89322.png"),
  Chrome: require("../../../assets/figma/search/6a419.png"),
  Yellow: require("../../../assets/figma/search/f2cda.svg"),
  Glitter: require("../../../assets/figma/search/fbf74.png"),
  Multi: require("../../../assets/figma/search/92737.png"),
};
