import {beforeEach,it,expect,vi} from 'vitest'
const mock=vi.hoisted(()=>({get:vi.fn(),directory:vi.fn(),details:vi.fn(),rpc:vi.fn()}));
vi.mock('@/lib/auth',()=>({serviceClient:{rpc:mock.rpc}}));vi.mock('@/lib/admin/data',()=>({adminGet:mock.get}));vi.mock('@/lib/admin/users',()=>({userDirectory:mock.directory,userDetails:mock.details}));
import {prepareExport,csvRows,recordExport} from '@/lib/admin/export'
const owner={user:{id:'owner'},role:'owner',permissions:['users','overview','bookings']},support={...owner,role:'support'};
beforeEach(()=>{vi.resetAllMocks();mock.directory.mockResolvedValue([{id:'a',email:'test@example.invalid'}]);mock.rpc.mockResolvedValue({data:null});mock.get.mockResolvedValue({items:[{id:'b'}],hasMore:false})})
it('rejects Support user exports before querying any user data',async()=>{await expect(prepareExport(support,{section:'users',reason:'Support test'})).rejects.toMatchObject({status:403});expect(mock.directory).not.toHaveBeenCalled();await expect(prepareExport(support,{section:'credits',reason:'Support test'})).rejects.toMatchObject({status:403})})
it('exports all filtered user pages and detects the cap instead of silently truncating',async()=>{const page=Array.from({length:500},(_,i)=>({id:i}));mock.directory.mockResolvedValueOnce(page).mockResolvedValueOnce([{id:'last'}]);const f=await prepareExport(owner,{section:'users',reason:'Account review',q:'test@',filter:'user'});expect(f.count).toBe(501);expect(mock.directory.mock.calls[1][1]).toMatchObject({offset:500,q:'test@',filter:'user'});mock.directory.mockResolvedValue(page);await expect(prepareExport(owner,{section:'users',reason:'Account review'})).rejects.toMatchObject({status:422})})
it('quotes commas/newlines and neutralizes spreadsheet formulas including whitespace prefixes',()=>{const csv=csvRows([{a:'=HYPERLINK("bad")',b:' \t+SUM(1,2)',c:'normal\ntext'}]);expect(csv).toContain(`"'=HYPERLINK(""bad"")"`);expect(csv).toContain(`"' \t+SUM(1,2)"`);expect(csv).toContain('"normal\ntext"')})
it('keeps overview aggregated, uses the chosen range and requires audit before release',async()=>{mock.get.mockResolvedValue({counts:{users:2}});const f=await prepareExport(owner,{section:'overview',reason:'Trend analysis',days:7});expect(f.type).toBe('application/json');expect(mock.get.mock.calls[0][2].get('days')).toBe('7');await recordExport(owner,f);expect(mock.rpc).toHaveBeenCalledWith('admin_export_log',expect.objectContaining({p_section:'overview',p_count:1}));mock.rpc.mockResolvedValue({error:{message:'secret'}});await expect(recordExport(owner,f)).rejects.toMatchObject({status:403})})
it('rejects missing reasons, arbitrary columns/tables and non-account detail IDs',async()=>{for(const body of[{section:'users',reason:''},{section:'users',reason:'Valid reason',columns:'*'},{section:'auth',reason:'Valid reason'},{section:'users',reason:'Valid reason',id:'bad'}])await expect(prepareExport(owner,body)).rejects.toThrow()})
