export type Profile = {
  id: string;
  display_name: string | null;
  nail_shape?: string | null;
  occasions?: string[] | null;
  nail_techniques?: string[] | null;
  username: string | null;
  avatar_url: string | null;
  banner_url?: string | null;
  bio: string | null;
  specialties?: string[] | null;
  location: string | null;
  booking_area?: string | null;
  account_type: "user" | "creator" | "salon";
  is_private: boolean;
  onboarding_complete: boolean;
  credit_balance: number;
  subscription_tier: string | null;
  subscription_status: string | null;
  is_pro: boolean;
};
export type Design = {
  id: string;
  title: string;
  description: string | null;
  image_url: string | null;
  created_by: string;
  category: string | null;
  shape: string | null;
  length: string | null;
  technique: string | null;
  occasion: string | null;
  saves_count: number;
  is_published: boolean;
  created_at: string;
};
export type Service = {
  id: string;
  creator_id: string;
  name: string;
  description: string | null;
  price: number;
  deposit_amount: number;
  duration_minutes: number;
  is_active: boolean;
};
export type Booking = {
  id: string;
  client_id: string;
  creator_id: string;
  service_id: string;
  booking_date: string;
  start_time: string;
  end_time: string;
  starts_at: string | null;
  ends_at: string | null;
  time_zone: string | null;
  status: "pending" | "confirmed" | "declined" | "cancelled";
  deposit_paid: boolean;
  reference_design_id: string | null;
  notes: string | null;
  services?: Service;
  price_snapshot?: number;
  deposit_snapshot?: number;
  location_snapshot?: string;
};
export type Slot = {
  client_calendar_state?: "checked" | "disconnected" | "unavailable";
  client_calendar_conflict?: boolean;
  start_time: string;
  end_time: string;
  starts_at: string;
  ends_at: string;
  available: boolean;
};
export type Conversation = {
  id: string;
  client_id: string;
  creator_id: string;
  last_message_at: string;
  muted_by?: string[];
};
export type Message = {
  id: string;
  conversation_id: string;
  sender_id: string;
  content: string;
  created_at: string;
  is_read: boolean;
  design_id?: string | null;
  image_path?: string | null;
};
export type Generation = {
  id: string;
  image_url: string;
  shape: string;
  length: string;
  vibe: string[];
  created_at: string;
};
